### ISSUE TITLE
Create this repository

### ISSUE THREAD

**Issue by prestonvanloon** [angulartics/angulartics-newrelic-insights#1]
Can this repository be created and publish to bower/npm? It would be helpful for projects using this plugin and dependency managers.

**Comment by prestonvanloon** [comment]
Created here https://github.com/prestonvanloon/angulartics-newrelic-insights

**Comment by gampleman** [comment]
Hey @prestonvanloon, looks like I don't actually get notified yet for this repo. If you want it in the official repo, i.e. here, could you send a PR?

**Comment by prestonvanloon** [comment]
@gampleman, I can't create a PR since there are no commits or anything to fork.

**Comment by gampleman** [comment]
Ah ok, I'll just download your repo and push here if you're ok with that?

**Comment by prestonvanloon** [comment]
Sure

**Comment by gampleman** [comment]
OK done. I wonder how to deal with npm publishing?

**Comment by prestonvanloon** [comment]
How is that normally handled in the org? I can add whoever as a collaborator in npm

**Comment by gampleman** [comment]
Not sure. If you add me I'll add a token to the .travis file and have it publish on new tags. That way we can publish releases with minimal hassle (although so far the code has changed minimally).

**Comment by prestonvanloon** [comment]
Added

**Comment by prestonvanloon** [comment]
@gampleman, I created PR for npm token #2
